# `sqsQueues` defines a list of objects, each of which specifies the queue that
# the connector will observe
sqsQueues:
  - # `url` specifies the URL of an SQS queue. This parameter is optional if
    # `name` is not empty, otherwise this parameter takes precedence against any
    # other parameter that refers to an SQS queue.
    url: 'https://sqs.us-east-1.amazonaws.com/1234567890/queue-name'
    # `name` specified the name of an SQS queue. If the `awsAccountId` parameter
    # is left empty, the library will obtain the queue URL using the AWS account
    # ID of the authenticated account. This parameter is optional, since it's
    # ignored when `url` is not empty.
    name: ''
    # `awsAccountId` can point to an AWS account different than the
    # authenticated one. This parameter is ignored when `name` is ignored.
    awsAccountId: ''
    # For future use cases. Currently ignored, since the FIFO property can be
    # inferred from the queue name: if the name ends in `.fifo` then it's a FIFO
    # queue.
    isFifo: false

image:
  repository: ghcr.io/openfaas-sqs-connector
  tag: 1.1.0

logLevel: warn

maxNumberOfMessages: 1
maxWaitTime: 1
visibilityTimeout: 30

openfaasGatewayUrl: http://gateway.openfaas.svc:8080
replicaCount: 1
topicRefreshInterval: 15

resources: {}
