---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Release.Namespace | quote }}
  labels:
{{ include "openfaas-sqs-connector.labels" . | indent 4 }}
  name: {{ template "openfaas-sqs-connector.serviceAccount.name" . }}
  annotations:
{{ include "openfaas-sqs-connector.serviceAccount.name" . }}
