{{- if .Values.serviceAccount.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.serviceAccount.name }}
  labels:
{{ include "openfaas-sqs-connector.labels" . | indent 4 }}
  annotations:
    {{- .Values.serviceAccount.annotations | toYaml | nindent 4 -}}
{{- end -}}
